FROM python:3.8

RUN apt-get update -y && apt-get upgrade -y
RUN python -m pip install --upgrade pip

RUN apt-get install chromium=90.0.4430.212-1 -y
RUN apt-get install chromium-driver=90.0.4430.212-1 -y

WORKDIR /app
COPY requirements-base.txt .
RUN python -m pip install -r requirements-base.txt

ENTRYPOINT [ "python" ]
