FROM python:3.8

# MAINTANER Your Name "youremail@domain.tld"

RUN apt-get update -y && apt-get upgrade -y
RUN python -m pip install --upgrade pip
RUN python -m pip install poetry
RUN python -m pip install --ignore-installed idna

ENV google_chrome_version="92.0.4515.159-1"
ENV chromedriver_version="92.0.4515.107"
RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${google_chrome_version}_amd64.deb
RUN wget --no-verbose -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${chromedriver_version}/chromedriver_linux64.zip
RUN apt install -y /tmp/chrome.deb
RUN unzip /tmp/chromedriver.zip -d app

# We copy just the requirements.txt first to leverage Docker cache
COPY ./pyproject.toml ./poetry.lock app/

WORKDIR /app
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction
COPY app.py .
COPY display_helpers.py il_tickers.py portfolio.py /app/
COPY portfolio.csv .

ENTRYPOINT [ "python" ]
CMD [ "app.py" ]
