FROM portfolio-gain-armv7:base

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY app.py .
COPY templates templates/
COPY display_helpers.py il_tickers.py portfolio.py ./
COPY *.csv .

ENTRYPOINT [ "python" ]
CMD [ "app.py" ]
